version: '3.8'
services:
  firefox:
    image: selenium/standalone-firefox
    shm_size: 2gb
    ports:
      - 4444:4444
    healthcheck:
      test: geckodriver --version

  firefox_video:
    image: selenium/video
    volumes:
      - ./videos:/videos
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - FILE_NAME=firefox_video.mp4

  nightwatch:
    build: .
    init: true
    network_mode: host
    environment:
      - BROWSER=firefox
    depends_on:
      firefox:
        condition: service_healthy
