version: '3.8'
services:
  edge:
    image: selenium/standalone-edge
    shm_size: 2gb
    ports:
      - 4444:4444
    healthcheck:
      test: msedgedriver --version

  edge_video:
    image: selenium/video
    volumes:
      - ./videos:/videos
    depends_on:
      - edge
    environment:
      - DISPLAY_CONTAINER_NAME=edge
      - FILE_NAME=edge_video.mp4

  nightwatch:
    build: .
    init: true
    network_mode: host
    environment:
      - BROWSER=edge
    depends_on:
      edge:
        condition: service_healthy
