version: '3.8'
services:
  edge:
    image: selenium/standalone-edge
    shm_size: 2gb
    ports:
      - 4444:4444
    healthcheck:
      test: msedgedriver --version

  nightwatch:
    build: .
    init: true
    network_mode: host
    environment:
      - BROWSER=edge
    depends_on:
      edge:
        condition: service_healthy
